apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hazelcastenterprises.hazelcast.com
  labels:
    app.kubernetes.io/name: hazelcast
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator

    # hazelcast and role labels for project-to-project communications via NetworkPolicy
    hazelcast: "true"
    role: hazelcast
spec:
  group: hazelcast.com
  names:
    kind: HazelcastEnterprise
    listKind: HazelcastEnterpriseList
    plural: hazelcastenterprises
    singular: hazelcastenterprise
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
